routes/my_routes_admin.py
from flask import Blueprint, flash, url_for, redirect
from flask_login import current_user, login_required
from forms.forms import DeleteUserForm, LockUser, EditUserForm
from datetime import timedelta
from models.models import Users, Transaction, db, SupportTickets, LockedUsers, Loans
from sqlalchemy import func, and_, case, asc
import pandas as pd
import matplotlib.pyplot as plt
import io
import base64
from routes.transfer import admin_required, logger
from flask import render_template, request



transactions_filter_bp = Blueprint('transactions_filter_bp', __name__)

@transactions_filter_bp.route('/transactions_filter', methods=['GET', 'POST'])
@login_required
@admin_required  
def transactions_filter():
    """
    Renders a transaction management page with functionality to filter transactions based on various criteria.

    On a POST request it filters transactions based on the specified criteria, including user ID, date range, and transaction type.
    The function requires the user to be logged in and have administrative privileges to access and perform the filtering.

    The filtering criteria are provided through form inputs and include:
    - User ID: Filters transactions for a specific user.
    - Date range (From and Until): Filters transactions within the specified date range.
    - Transaction type: Filters transactions of a specific type.

    After applying the filters, the function renders the transaction management page, displaying the filtered results
    alongside all transactions for comparison and review.

    Returns:
        render_template: The 'transaction_management.html' template populated with the filtered transactions.
    """
    
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        date_from = request.form.get('date_from')
        date_until = request.form.get('date_until')
        transaction_type = request.form.get('transaction_type')

        query = Transaction.query

        # Filtering by user ID
        if user_id:
            query = query.filter(Transaction.user_id == user_id)

        # Filter by date range
        if date_from:
            query = query.filter(Transaction.transaction_date >= date_from)
        if date_until:
            query = query.filter(Transaction.transaction_date <= date_until)

        # Filtering by transaction type if other than 'all' is selected
        if transaction_type and transaction_type != 'all':
            query = query.filter(Transaction.transaction_type == transaction_type)

        # Results
        transactions = query.all()

        return render_template('transaction_management.html', transactions=transactions)

    return render_template('transaction_management.html')





def count_log_levels(file_path):
    """
    Counts the occurrences of different log levels in a log file.

    This function reads a log file specified by `file_path` and counts the occurrences of log levels such as INFO,
    ERROR, WARNING, and CRITICAL within the file. It returns a dictionary with the log levels as keys and the counts
    as values.

    Parameters:
    - file_path (str): The path to the log file to be analyzed.

    Returns:
    - dict: A dictionary with keys corresponding to the log levels ("INFO", "ERROR", "WARNING", "CRITICAL") and
      integer values representing the number of times each log level appears in the file.

    Example:
    If the log file contains two INFO messages, one ERROR message, and one WARNING message, the function will return:
    {"INFO": 2, "ERROR": 1, "WARNING": 1, "CRITICAL": 0}

    Note:
    The function assumes that each line in the log file contains at most one log level. It does not count multiple
    occurrences of log levels within a single line. The search for log level strings is case-sensitive.
    """
    log_levels = {"INFO": 0, "ERROR": 0, "WARNING": 0, "CRITICAL": 0}

    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            if "INFO" in line:
                log_levels["INFO"] += 1
            elif "ERROR" in line:
                log_levels["ERROR"] += 1
            elif "WARNING" in line:
                log_levels["WARNING"] += 1
            elif "CRITICAL" in line:
                log_levels["CRITICAL"] += 1

    return log_levels



def plot_to_html_img(plt):
    """
    Converts a matplotlib plot to an HTML image tag with a base64-encoded PNG image.

    This function takes a matplotlib plot object, saves it as a PNG image to a bytes buffer, then encodes the image
    to a base64 string. This string is embedded into an HTML image tag, allowing the plot to be displayed directly
    in web browsers or any HTML-supporting environment without needing a separate file.

    Parameters:
    - plt (matplotlib.pyplot): The plot object created using matplotlib that needs to be converted.

    Returns:
    - str: An HTML image tag containing the base64-encoded PNG image of the plot.

    Note:
    - This function requires the `io` and `base64` modules to be imported.
    - It's important to call plt.close() after using this function to release memory if you're generating many plots.
    """
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    image_base64 = base64.b64encode(buf.getvalue()).decode('utf-8').replace('\n', '')
    buf.close()

    return f'<img src="data:image/png;base64,{image_base64}"/>'




reports_and_statistics_bp = Blueprint('reports_and_statistics_bp', __name__)

@reports_and_statistics_bp.route('/reports_and_statistics', methods=['GET', 'POST'])
@login_required
@admin_required
def reports_and_statistics():
    """
    Generates a comprehensive report and statistics for various aspects of the system, including user roles, nationalities,
    support ticket priorities, transaction types, average transaction values, response times for support tickets,
    priority counts for support tickets, log levels, and loan types. It visualizes this data using pie charts and bar charts,
    converting them into HTML images for easy display in a web interface.

    This function queries the database for specific data sets, processes and analyzes the data using Pandas, and then
    visualizes the results using Matplotlib. The visualizations are converted to HTML images that can be directly embedded
    in the web page rendered by Flask. Additionally, the function calculates average response times for support tickets
    and categorizes support tickets by priority, preparing all necessary information for display on the reports and statistics page.

    Operations performed:
    1. Queries and visualizes the distribution of user roles.
    2. Queries and visualizes the distribution of user nationalities.
    3. Queries and visualizes the distribution of support ticket priorities based on unique reference numbers.
    4. Queries and visualizes the distribution of transaction types.
    5. Calculates and visualizes the average transaction value for each transaction type.
    6. Calculates the average response time between the first and second records for unique support ticket reference numbers.
    7. Counts and prepares support tickets by priority level for display.
    8. Counts the occurrences of different log levels in a log file and visualizes this distribution.
    9. Queries and visualizes the distribution of loan types.

    The results of these operations are passed to the 'reports_and_statistics.html' template, along with additional data
    like average response time, priority counts, log counts, and visualizations as context variables for rendering.

    Returns:
    - render_template: Renders the 'reports_and_statistics.html' template with context variables including
      charts (as HTML images), average response time, counts of support tickets by priority, log counts, and more.

    Requires:
    - Flask login_required and admin_required decorators to ensure that only logged-in and authorized (admin) users
      can access this function.
    - SQLAlchemy for database queries.
    - Pandas for data processing and analysis.
    - Matplotlib for data visualization.
    """
    # Downloading data about user roles
    roles_count = Users.query.with_entities(Users.role, func.count(Users.role)).group_by(Users.role).all()

    # Creting DataFrame
    roles_df = pd.DataFrame(roles_count, columns=['Role', 'Count'])

    # Create a pie chart
    fig, ax = plt.subplots(figsize=(4, 3))
    ax.pie(roles_df['Count'], labels=roles_df['Role'], autopct='%1.1f%%', startangle=140)
    ax.set_title('Distribution of user roles in the system')

    # Changing the background color
    ax.set_facecolor('black')
    # Changing the background color of the figure
    fig.patch.set_facecolor('lightgrey')
    
    # Convert chart to HTML img
    chart1 = plot_to_html_img(plt)
    
    
    
    
    # Retrieving data about user nationalities
    countries_count = Users.query.with_entities(Users.country, func.count(Users.country)).group_by(Users.country).all()
    
    #Creating dataframe
    countries_df = pd.DataFrame(countries_count, columns = ['Country', 'Count'])
    
    # Create a pie chart
    fig, ax = plt.subplots(figsize=(4, 3)) 
    ax.pie(countries_df['Count'], labels=countries_df['Country'], autopct='%1.1f%%', startangle=140)
    ax.set_title('Distribution of user nationalities in the system')

    
    ax.set_facecolor('black') 
    fig.patch.set_facecolor('lightgrey')  
    
    # Convert chart to HTML img
    chart2 = plot_to_html_img(plt)
    
    
    # Subquery to extract unique reference numbers with their priorities
    # Podzapytanie do wyodrębnienia unikalnych numerów referencyjnych z ich priorytetami
    subquery = (db.session.query(SupportTickets.reference_number, SupportTickets.priority)
                .distinct(SupportTickets.reference_number)
                .subquery())
    
    # Master Query - Priority grouping and counting based on unique reference numbers

templates/account_data.html
<!--  account_data.html  -->


{% extends 'base2.html' %}


{% block title %} Imperial Bank - user dashboard - account data {% endblock %}


{% block precontent %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
    <p>Your fast messages: {{ message }}</p>
{% endfor %}
{% endif %}
{% if not messages %}
    <p>Your fast messages: ---</p>
{% endif %}
{% endwith %}

<h4>Your user account details:</h4>
    <table border="1" class="center-table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Role</th>
          <th>Email</th>
          <th>Phone number</th>
          <th>Country</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.role }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.phone_number }}</td>
            <td>{{ user.country }}</td>
          </tr>
      </tbody>
    </table>
    <br>

    <h3>Edit your data:</h3><br>

    <form action="{{ url_for('edit_profile_bp.edit_profile') }}" method="post" role="form">

      <label for="email">Email:</label>
      <input type="text" id="email" name="email" value="{{ current_user.email }}" required><br>

      <label for="phone_number">Phone number:</label>
      <input type="text" id="phone_number" name="phone_number" value="{{ current_user.phone_number }}" required><br>


      <label for="country">Country:</label>
      <input type="text" id="country" name="country" value="{{ current_user.country }}" required><br><br>

      <!-- Hidden field with CSRF token -->
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      

      <input type="submit" value="Update"><br><br>
      <img src="static/{{ user.username }}.jpg">
    </form>

    
{% endblock %}


{% block content %}

{% endblock %}

templates/account_locked.html
<!-- templates/account_locked.html -->
{% extends 'base.html' %}

{% block content %}
<h1>Bank account has been blocked!</h1><br><br>
<p>Yout bank account for user {{ locked_user.username }}  has been blocked. <br><br>
    Please contact our customer service department by phone.</p>

<p><big>Phone number: +44 123 456 78</big></p>

{% endblock %}

templates/admin_dashboard_cm.html
<!--  admin_dashboard_cm.html (admin's website) -->

{% extends 'base_admin.html' %}
{% block title %}Imperial Bank - Admin Dashboard - Customer Management {% endblock %}
{% block subtitle %} - Customer Management{% endblock %}


{% block content %}
<br>

<div class="container2">
    <div class="left2">

        <h3>Add New Customer</h3>

        <form action="{{ url_for('add_customer_bp.add_customer') }}" method="post" role="form">

            
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required><br>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required><br>
            
            <!-- Hidden field with CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

            <label for="role">Role:</label>
            <select id="role" name="role" required>
            <option value="client">Client</option>
            <option value="bank_emploee">Bank employee</option>
            <option value="board_member">Board Member</option>
            <option value="management">Management</option>
            </select><br>

            <label for="email">Email:</label>
            <input type="text" id="email" name="email" required><br>

            <label for="phone_number">Phone number:</label>
            <input type="text" id="phone_number" name="phone_number" required><br>

            <label for="country">Country:</label>
            <input type="text" id="country" name="country" required><br>
            
            <input type="submit" value="Add Customer">
        </form> 

    </div>

    <div class="right2">
        <!-- Table with customer information -->

        <h3>Users database:</h3> <br>
        <table border="1" >
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Role</th>
                <th>Email</th>
                <th>Phone number</th>
                <th>Country</th>
            </tr>
            </thead>
            <tbody>
            {% for user in all_users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.role }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.phone_number }}</td>
                    <td>{{ user.country }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

<hr>


<div class="container2">
    <div class="left2">
        <h3>Add First Transaction for new user:</h3>

        <form action="{{ url_for('create_transaction_bp.create_transaction') }}" method="post" role="form">

            <label for="user_id">User ID:</label>
            <input type="number" id="user_id" name="user_id" required><br>

            <label for="transaction_date">Transaction Date:</label>
            <input type="date" id="transaction_date" name="transaction_date" required><br>

            <label for="transaction_type">Transaction Type:</label>
            <select id="transaction_type" name="transaction_type" def required>
            
            <option value="DEB">Debit</option>
            <option value="DD">Direct Debit</option>
            <option value="SAL">Salary</option>
            <option value="CSH">Cash</option>
            <option value="SO">Standing Order</option>
            <option value="FPI">Faster Payment Incoming</option>
            <option value="FPO">Faster Payment Outgoing</option>
            <option value="MTG">Mortgage</option>

            </select><br>

            <label for="sort_code">Sort Code:</label>
            <input type="text" id="sort_code" name="sort_code" required><br>

            <label for="account_number">Account Number:</label>
            <input type="text" id="account_number" name="account_number" required><br>

            <label for="transaction_description">Description:</label>
            <input type="text" id="transaction_description" name="transaction_description" required><br>

            <label for="debit_amount">Debit Amount:</label>
            <input type="number" step="0.01" id="debit_amount" name="debit_amount"><br>

            <label for="credit_amount">Credit Amount:</label>
            <input type="number" step="0.01" id="credit_amount" name="credit_amount"><br>

            <label for="balance">Balance:</label>
            <input type="number" step="0.01" id="balance" name="balance" required><br>

            <!-- Hidden field with CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

            <input type="submit" value="Add Transaction">

        </form>
        

    </div>

    <div class="right2">
        <!-- delete_user -->
        <h3>Delete existing user:</h3>

        <form action="{{ url_for('delete_user_bp.delete_user') }}" method="post">
            <label for="username">User to delete - Name:</label>
            <input type="text" id="username" name="username" required> <br><br>
            
            <!-- Hidden field with CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

            <input type="submit" value="Delete user">
        </form>
        <br><br>

        {% if user_to_delete and transactions_count > 0 %}
        <form action="{{ url_for('delete_transactions_bp.delete_transactions', user_id=user_to_delete.id) }}" method="post">
            <input type="submit" value="Delete all user's transactions">
            <!-- Hidden field with CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
        <br><br>

        <form action="{{ url_for('admin_dashboard_cm') }}" method="post">
            <input type="submit" value="Back to admin's panel">
            <!-- Hidden field with CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>



        {% endif %}

        <hr>


        <!-- Changing the password for the user: List of users with link to change password -->
        <h3>Password change:</h3>
        <a href="{{ url_for('list_users') }}" class="link">Password change</a> <br>
        
    </div>
</div>
    
{% endblock %}

templates/apply_car_loan.html
<!--  apply_car_loan.html ( on this website user can confirm car loan ) -->


{% extends 'base2.html' %}

{% block title %} Imperial Bank - Apply for car loan {% endblock %}




{% block precontent %}

Car Loan <br>

{% endblock %}

templates/author.html
<!-- author.html  -->

{% extends 'base.html' %}

{% block title %}Imperial Bank - Online Banking - project's author {% endblock %}


{% block content %}
<div class="container">
    <div>
        <img src="static/marcin-autor.jpg">
    </div>

    <div class="left4" style="padding-left: 30px; padding-right: 30px;">
        <h4>Hello.
            <p>If you are reading it you probably want to know what value I will bring to your company or to the company you cooperate with or recruit for. </p>
            
            <p>Patience and logical thinking skills are my greatest advantages. They constitute the foundation for my future work.</p> 
            <p>I like to create systems, processes and functionalities. I prefer backend ;)</p>
            <p>I'm a homebody type. I have a set daily routine.</p>
            <p>I'm from Poland. I have been living in England since 2010. I completed my higher education in 2006 at the Casimir the Great University in Bydgoszcz.</p>
            <p>If you want to learn more about me, don't hesitate to contact me.</p></h4>
    </div>

    <div>
        <h3>Links:</h3>

        <h3><a href="https://github.com/Marcin-Lewandowski" >Github</a></h3>

        <h3><a href="https://www.linkedin.com/in/marcinlewandowski2/" >Linkedin</a></h3>

        <h3><a href="mailto:telfordmarcin@gmail.com">Email</a></h3>

        <b>telfordmarcin(O.O)gmail.com</b>
    </div>
</div>
{% endblock %}

templates/base2.html
<!--  base2.html - base for all user's subpages excluding help center subpages -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">  
    
</head>
<body>
    <header>
        <div class="container5">
            <div class="left4">
                <!-- <img src="static/imperial-bank-2.jpg" alt="Imperial Bank"> -->
                <img src="{{ url_for('static', filename='imperial-bank-2.jpg') }}">

            </div>

            <div class="right4">
                <p>Welcome, {{ current_user.username }}!</p>
                
            </div>
            <div class="right4">
                <a href="{{ url_for('logout') }}"><img src="{{ url_for('static', filename='logout.jpg') }}"> </a>
                

            </div>
        </div>
        
    </header>

    <nav>
        
    </nav>

    <main>
        <div class="container5">
            <div class="left5">
                <div class="container100">

                    <div class="visa">
                        <img src="{{ url_for('static', filename='visa.jpg') }}">
        
                    </div>
                    <div class="visa2">
                        <h3>Standard Save & Spend Account</h3>
                        <h4>Sort code: {{ last_transaction.sort_code }}  <br>
                        Account number: {{ last_transaction.account_number }}</h4>
                    </div>

                    <div class="visa3">
                        <h3>Funds available:</h3>
                        <h2> £ {{ last_transaction.balance }}</h2>
                    </div>

                </div>

                <div class="container100">

                    <h4>
                        
                    <a href="{{ url_for('dashboard') }}"> Statement</a>&nbsp | &nbsp

                    <a href="{{ url_for('my_loans') }}"> My loans</a>  &nbsp | &nbsp

                    <a href="{{ url_for('make_payment') }}"> Make a payment</a>  &nbsp | &nbsp

                    <a href="{{ url_for('add_recipient_bp.add_recipient') }}"> Add new recipient</a>  &nbsp | &nbsp

                    <a href="{{ url_for('online_shop') }}"> Online shop</a>  &nbsp | &nbsp &nbsp

                    <a href="{{ url_for('account_data') }}"> Account data</a>  &nbsp | &nbsp 

                    <a href="{{ url_for('ddso_bp.ddso') }}"> Direct Debit & Standing orders</a> </h4>

                </div>
                <div class="center">
                    {% block precontent%}

                    {%  endblock %}

                </div>
            </div>

            <div class="right5">
                <div class="center">
                    <h3>Check your messages: </h3>
                    <a href="{{ url_for('help_center') }}" > Help and support center</a><br><br>
                    
                    <hr>
                    
                    
                    <h3>Borrowing: </h3>
                    <a href="{{ url_for('loans') }}" > Loans </a> <br><br>
                    
                    <hr> 
                    
                    <h3>Contact</h3>
                    Hotline: +44123678909 <br><br>
                    Email: info@ib.co.uk
                    

                </div>
                
            </div>
        </div>

        {% block content %}
            
        {% endblock %}
        
    </main>

    <footer>
        
    </footer>
   
</body>
</html>

templates/car_loan.html
<!--  car_loan.html ( on this website user can take out a car loan ) -->


{% extends 'base2.html' %}

{% block title %} Imperial Bank - Car Loan {% endblock %}


{% block precontent %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
    <p>Your fast messages: {{ message }}</p>
{% endfor %}
{% endif %}
{% if not messages %}
    <p>Your fast messages: ---</p>
{% endif %}
{% endwith %}

<div class="container2">

    <div class="left2">
        <h3>Car loan details:</h3>
        <table border="1" >
            <tbody>

                <tr>
                    <td>Currency code </td>
                    <td>GBP</td>
                </tr>
                
                <tr>
                    <td> Nominal amount </td>
                    <td>£ 8000</td>
                </tr>
    
                <tr>
                    <td> Annual interest </td>
                    <td> 6 %</td>
                </tr>

                <tr>
                    <td>Interest type </td>
                    <td>Fixed</td>
                </tr>
    
                <tr>
                    <td>Installment amount </td>
                    <td>£ 706.67</td>
                </tr>

                <tr>
                    <td>Installment numbers </td>
                    <td>12</td>
                </tr>

                <tr>
                    <td>Loan cost </td>
                    <td>£ 480</td>
                </tr>

                <tr>
                    <td>Total amount to be repaid </td>
                    <td>£ 8480</td>
                </tr>

                <tr>
                    <td>Loan purpose </td>
                    <td>Car purchase</td>
                </tr>
            </tbody>
          </table>




    </div>

    <div class="right2">
        <h3>Loan Repayment Terms</h3>
        
        <b>1. Amount and Duration:</b> The Borrower agrees to repay the total loan amount along with accrued interest, as per the agreed-upon repayment schedule, 
        which shall not exceed a term of [insert term here] years/months from the date of the loan disbursement.<br><br>

        <b>2. Repayment Schedule:</b> Repayments are due in monthly installments on the [insert day] of each month, starting from [insert start date] until the loan is fully repaid. 
        Each installment includes both principal and interest components.<br><br>

        <b>3. Interest Rate:</b> The annual interest rate on the loan is [insert interest rate]%, calculated on a [insert method, e.g., fixed or reducing] basis. 
        The exact amount of interest payable will be detailed in the repayment schedule.<br><br>

        <b>4. Early Repayment:</b> The Borrower may choose to repay the loan in full or in part before the due date without incurring any early repayment fees.<br><br>

        <b>5. Late Payment Penalties:</b> Any payments not made within [insert number of days] days of the due date will incur a late payment fee of [insert fee amount] 
        plus additional interest on the overdue amount at the rate of [insert penalty interest rate]% per annum. <br>


        <h2><a href="{{ url_for('apply_car_loan_bp.apply_car_loan') }}"> Apply for Car Loan</a></h2>

        <h3><a href="{{ url_for('my_loans') }}"> Go to - My Loans</a></h3>


    </div>
</div>

{% endblock %}

templates/dmfq.html
<!--  dmfq.html ( delete messages for query) -->


{% extends 'base3.html' %}


{% block title %} Imperial Bank - Help and cupport center - deleting messages for query {% endblock %}

{% block precontent%}

<h2 style="color: red;">Warning! You trying to delete your query - Reference number {{ query.reference_number }}</h2>

<h3>There is {{ messages_quantity }} messages in your query.</h3>
<h3>Are you sure you want to delete all messages?</h3>
<br><br>

<form action="{{ url_for('delete_query_confirmation_bp.delete_query_confirmation' , query_ref=query.reference_number) }}" method="post" role="form">

    <!-- Hidden field with CSRF token -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <input type="submit" value="YES - delete all messages" style="width: 200px; height: 40px; font-size: 16px; cursor: pointer;">
</form> <br><br>

<h3>
    <a href="{{ url_for('help_center' ) }}">NO - back to Help Center</a>
</h3>
{%  endblock %}

templates/list_users.html
<!--  list_users.html (all users list with links to change password ) -->

{% extends 'base_admin.html' %}
{% block title %}Imperial Bank - Admin Dashboard - Customers list {% endblock %}
{% block subtitle %} - Customers List{% endblock %}


{% block content %}
    <h2>Users:</h2>
    
    {% for user in all_users %}
        {{ user.username }} - <a href="{{ url_for('change_password', user_id=user.id) }}">Change Password</a> <br>


    {% endfor %}
    
{% endblock %}

templates/transaction_management.html
<!--  transaction_management.html (admin's webpage - this page is used to filter transactions of a specific system user.) -->



{% extends 'base_admin.html' %}
{% block title %}Imperial Bank - Admin Dashboard - Transaction Management {% endblock %}
{% block subtitle %} - Transaction Management{% endblock %}

{% block content %}

<center>
    <h2>Filter transactions for specific user: </h2>
<form action="{{ url_for('transactions_filter_bp.transactions_filter') }}" method="post" role="form">
    
    <!-- Hidden field with CSRF token -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>


    <label for="user_id">User ID:</label>
    <input type="number" id="user_id" name="user_id" required><br>

    <label for="transaction_date">Transaction Date: From</label>
    <input type="date" id="transaction_date" name="transaction_date" required><br>

    <label for="transaction_date">Transaction Date: Until</label>
    <input type="date" id="transaction_date" name="transaction_date" required><br>

    <label for="transaction_type">Transaction Type:</label>
    <select id="transaction_type" name="transaction_type" def required>
    
    <option value="all">All</option>
    <option value="DEB">Debit</option>
    <option value="DD">Direct Debit</option>
    <option value="SAL">Salary</option>
    <option value="CSH">Cash</option>
    <option value="SO">Standing Order</option>
    <option value="FPI">Faster Payment Incoming</option>
    <option value="FPO">Faster Payment Outgoing</option>
    <option value="MTG">Mortgage</option>
    </select><br><br>

    <input type="submit" value="Show transactions">
    
</form> 


<h2>Filtered Transactions</h2>
   
<table border="1" class="table-center">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Username</th>
            <th>Transaction Date</th>
            <th>Transaction Type</th>
            <th>Debit Amount</th>
            <th>Credit Amount</th>
            <th>Balance</th>
        </tr>
    </thead>
    <tbody>
        {% if transactions %}
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.user_id }}</td>
                    <td>{{ transaction.user.username }}</td>
                    <td>{{ transaction.transaction_date }}</td>
                    <td>{{ transaction.transaction_type }}</td>
                    <td>{{ transaction.debit_amount }}</td>
                    <td>{{ transaction.credit_amount }}</td>
                    <td>{{ transaction.balance }}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </tbody>
</table>

</center>
{% endblock %}